Add accurate postal code
silverorange/accessible-google-places-autocomplete pull request #17
Opened 2018-08-09 21:05 UTC by gauthierm

Adds reverse geocode lookup of postal code to get more accurate codes.

2018-08-09 21:06 UTC, gauthierm commented on src/AccessibleGooglePlacesAutocomplete.tsx
> +            resolve(geocodeResult[0]); // TODO get best match
Needs to be done before merge.

2018-08-10 13:00 UTC, nburka requested changes

2018-08-10 13:00 UTC, nburka commented on src/AccessibleGooglePlacesAutocomplete.tsx
> +          console.log(placeResult.address_components); // tslint:disable-line
remove `console.log` before merge

2018-08-10 13:00 UTC, nburka commented on src/AccessibleGooglePlacesAutocomplete.tsx
> +        if (useMoreAccuratePostalCode) {
it'd be nice if we could just do this _if_ the postal code wasn't already accurate. But I realize that would involve some custom checking like `if ((countryId === 'CA' && postalCode.length < 6) || (countryId === 'US' && postalCode.length < 5))` (pseudo-code). But it'd be faster/better/cheaper to use the correct postal code if returned the first time, which works in 90%+ cases.

2018-08-10 13:28 UTC, gauthierm commented on src/AccessibleGooglePlacesAutocomplete.tsx
> +        if (useMoreAccuratePostalCode) {
We can check if the original field has the type `postal_code_prefix` and then do the more accurate lookup.

2018-08-13 13:32 UTC, merged